### PR TITLE
h2 -> p

### PR DESCRIPTION
**Pull request by ughitsaaron**
header is unnecessary in template.

### CODE REVIEW

**Comment by kevinferri** [comment]
:+1:

**Comment by cruzanmo** [comment]
h2 seems more semantically accurate to me in this case. Is there any reason not to use h2? @gloddy might be the best to ask on the issue of h tags.

**Comment by ughitsaaron** [comment]
@cruzanmo [see](https://trello.com/c/AQaJGz8y/188-clay-share-repo-seo-scrub)

**Comment by gloddy** [comment]
@cruzanmo Share doesn't really need a section header since, in the context of an article, it's not really content in the article.
Shorter version: share buttons aren't content.

**Pull request merged**
